name: R-CMD-check

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  R-CMD-check:
    runs-on: ubuntu-latest
    steps:
      # Checkout the repository
      - uses: actions/checkout@v3

      # Set up R
      - name: Set up R
        uses: r-lib/actions/setup-r@v2

      # Install dependencies
      - name: Install dependencies
        run: |
          install.packages('devtools', repos = 'https://cloud.r-project.org')
          devtools::install_deps(dependencies = TRUE)

      # Install covr package
      - name: Install covr
        run: |
          install.packages('covr', repos = 'https://cloud.r-project.org')

      # Run R CMD check
      - name: Run R CMD check
        run: |
          devtools::check()

      # Upload coverage to Codecov
      - name: Upload coverage to Codecov
        run: |
          Rscript -e 'covr::codecov(token = Sys.getenv("CODECOV_TOKEN"))'
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
